/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.parthappm.ultimatix;

import org.openqa.selenium.By;
import org.openqa.selenium.ElementNotInteractableException;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WindowType;

public class App
{
	public static void main(String[] args)
	{
		System.out.println("Timesheet Browser Automation");
		UserProperties properties = UserProperties.getInstance();
		DriverHelper driver = new DriverHelper();

		try
		{
			// executing the script to enable password
			driver.get("https://www.ultimatix.net");
			String script = "document.getElementById(\"password-btn\").addEventListener(\"click\", function(e){passwordValue();e.stopPropagation();});";
			driver.executeScript(script);

			// authenticating
			String username = properties.getUsername();
			String password = properties.getPassword();
			if(!username.equals(""))
			{
				driver.findElement(By.id("form1")).sendKeys(username);
				driver.findElement(By.id("proceed-button")).click();
				driver.findElement(By.id("password-btn")).click();
				if (!password.equals(""))
				{
					driver.findElement(By.id("password-login")).sendKeys(password);
					driver.findElement(By.id("form-submit")).click();

					// open the timesheet tab
					driver.switchTo().newWindow(WindowType.TAB);
					driver.get("https://timesheet.ultimatix.net/timesheet/");

					// open the myapp tab
					driver.switchTo().newWindow(WindowType.TAB);
					driver.get("https://myapp.tcs.com");

					// opening the email tab
					driver.findElement(By.id("loginBtn")).click();
					driver.findElement(By.id(("protocolhandler-welcome.useLightVersionLink"))).click();
					driver.findElement(By.xpath("//*[@alt='TCS_Gmail']")).click();
				}
			}

			// waiting for user to fill the data before closing the browser
			driver.waitInfinite();
		}
		catch (NoSuchElementException | ElementNotInteractableException e)
		{
			try
			{
				// waiting for user to manually take control over the browser
				driver.waitInfinite();
			}
			catch (Exception ignored) {}
		}
		catch (Exception ignored) {}

		System.out.println("browser closed");
		driver.close();
	}
}
